export const QUERY_MESSAGES = "QUERY_MESSAGES"

export const QUERY_TESTIMONIALS = "QUERY_TESTIMONIALS";
export const ADD_TESTIMONIAL = "ADD_TESTIMONIAL";
export const REMOVE_TESTIMONIAL = "REMOVE_TESTIMONIAL";

export const QUERY_OWNER_INFO = "QUERY_OWNER_INFO";
export const UPDATE_OWNER_INFO = "UPDATE_OWNER_INFO";