export const SUBMIT_MESSAGE = "SUBMIT_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";

export const ADD_TESTIMONIAL = "ADD_TESTIMONIAL";
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL";
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL";

export const UPDATE_OWNER_INFO = "UPDATE_OWNER_INFO";