export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
// export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
// export const UPDATE_CURRENT_PROJECT = "UPDATE_CURRENT_PROJECT";